### ISSUE TITLE
Prediction of data using this network

### ISSUE THREAD

**Issue by chirag-orbittec** [nearbydelta/ScalaNetwork#1]
After training the data, Can we predict using this network, Is there any function provided?
If yes, can you please give me some information on that?

**Comment by nearbydelta** [comment]
Dear chirag-obittec,
Yes, it has ability to predict after training.
Following Scala's convention, a Network instance has **apply** function.
You can predict it using that function, for example:
```scala
val net: Network = .... // Trained network
val data: ScalarMatrix = .... // The input, which you want to predict
val predicted = net(data)
```
The last line can be replaced with  `net.apply(data)`.

**Actually, we do not maintain this repository, any more.** This is because this project was an experimental project and was not designed properly.
If you want to use much more stable version, we recommend [DeepSpark](https://github.com/nearbydelta/deepspark) which is modified from this project.
We should warn you that the latter project does not support **distributed** training. We removed it because for the mini-batch training, the communication cost is much greater than the computation time. Therefore it just reads the data from Spark, but still it is a quite good solution for training NN on Spark.
